var hierarchy =
[
    [ "FChannelConfig", "struct_f_channel_config.html", null ],
    [ "FChannelConfigWithInfoDto", "struct_f_channel_config_with_info_dto.html", null ],
    [ "FChannelGetOrCreateRequestDto", "struct_f_channel_get_or_create_request_dto.html", null ],
    [ "FChannelMemberDto", "struct_f_channel_member_dto.html", null ],
    [ "FChannelRequestDto", "struct_f_channel_request_dto.html", null ],
    [ "FChannelResponseDto", "struct_f_channel_response_dto.html", null ],
    [ "FChannelsResponseDto", "struct_f_channels_response_dto.html", null ],
    [ "FChannelState", "struct_f_channel_state.html", null ],
    [ "FChannelStateResponseFieldsDto", "struct_f_channel_state_response_fields_dto.html", [
      [ "FChannelStateResponseDto", "struct_f_channel_state_response_dto.html", null ]
    ] ],
    [ "FChatApi", "class_f_chat_api.html", null ],
    [ "FChatEvent", "struct_f_chat_event.html", [
      [ "FChannelEvent", "struct_f_channel_event.html", [
        [ "FMessageEvent", "struct_f_message_event.html", [
          [ "FMessageDeletedEvent", "struct_f_message_deleted_event.html", null ],
          [ "FMessageNewEvent", "struct_f_message_new_event.html", null ],
          [ "FMessageUpdatedEvent", "struct_f_message_updated_event.html", null ],
          [ "FReactionEvent", "struct_f_reaction_event.html", [
            [ "FReactionDeletedEvent", "struct_f_reaction_deleted_event.html", null ],
            [ "FReactionNewEvent", "struct_f_reaction_new_event.html", null ],
            [ "FReactionUpdatedEvent", "struct_f_reaction_updated_event.html", null ]
          ] ]
        ] ],
        [ "FTypingStartEvent", "struct_f_typing_start_event.html", null ],
        [ "FTypingStopEvent", "struct_f_typing_stop_event.html", null ]
      ] ],
      [ "FHealthCheckEvent", "struct_f_health_check_event.html", null ],
      [ "FUserPresenceChangedEvent", "struct_f_user_presence_changed_event.html", null ]
    ] ],
    [ "FChatSocketEvents", "class_f_chat_socket_events.html", null ],
    [ "FCommandDto", "struct_f_command_dto.html", null ],
    [ "FConnectRequestDto", "struct_f_connect_request_dto.html", null ],
    [ "FDeviceFieldsDto", "struct_f_device_fields_dto.html", null ],
    [ "FErrorResponseDto", "struct_f_error_response_dto.html", null ],
    [ "FEventDto", "struct_f_event_dto.html", null ],
    [ "FEventResponseDto", "struct_f_event_response_dto.html", null ],
    [ "FFilter", "struct_f_filter.html", null ],
    [ "FLocalEvent", "struct_f_local_event.html", [
      [ "FConnectionChangedEvent", "struct_f_connection_changed_event.html", null ],
      [ "FConnectionRecoveredEvent", "struct_f_connection_recovered_event.html", null ]
    ] ],
    [ "FMember", "struct_f_member.html", null ],
    [ "FMessage", "struct_f_message.html", null ],
    [ "FMessageDto", "struct_f_message_dto.html", null ],
    [ "FMessagePaginationParamsRequestDto", "struct_f_message_pagination_params_request_dto.html", null ],
    [ "FMessageRequestDto", "struct_f_message_request_dto.html", null ],
    [ "FMessageResponseDto", "struct_f_message_response_dto.html", null ],
    [ "FOwnUserDto", "struct_f_own_user_dto.html", null ],
    [ "FPaginationOptions", "struct_f_pagination_options.html", null ],
    [ "FPaginationParamsRequestDto", "struct_f_pagination_params_request_dto.html", null ],
    [ "FQueryChannelsRequestDto", "struct_f_query_channels_request_dto.html", null ],
    [ "FReaction", "struct_f_reaction.html", null ],
    [ "FReactionDto", "struct_f_reaction_dto.html", null ],
    [ "FReactionGroup", "struct_f_reaction_group.html", null ],
    [ "FReactionRequestDto", "struct_f_reaction_request_dto.html", null ],
    [ "FReactionResponseDto", "struct_f_reaction_response_dto.html", null ],
    [ "FReactions", "struct_f_reactions.html", null ],
    [ "FReadDto", "struct_f_read_dto.html", null ],
    [ "FSendEventRequestDto", "struct_f_send_event_request_dto.html", null ],
    [ "FSendMessageRequestDto", "struct_f_send_message_request_dto.html", null ],
    [ "FSendReactionRequestDto", "struct_f_send_reaction_request_dto.html", null ],
    [ "FSortOption", "struct_f_sort_option.html", null ],
    [ "FSortParamRequestDto", "struct_f_sort_param_request_dto.html", null ],
    [ "FUpdateMessageRequestDto", "struct_f_update_message_request_dto.html", null ],
    [ "FUser", "struct_f_user.html", null ],
    [ "FUserObjectDto", "struct_f_user_object_dto.html", null ],
    [ "FUserObjectRequestDto", "struct_f_user_object_request_dto.html", null ],
    [ "FUserRef", "struct_f_user_ref.html", null ],
    [ "IChatSocket", "class_i_chat_socket.html", null ],
    [ "UBottomReactionWidget", "class_u_bottom_reaction_widget.html", null ],
    [ "UChannelContextWidget", "class_u_channel_context_widget.html", null ],
    [ "UChatChannel", "class_u_chat_channel.html", null ],
    [ "UHeaderWidget", "class_u_header_widget.html", null ],
    [ "UMessageHoverMenuWidget", "class_u_message_hover_menu_widget.html", null ],
    [ "UMessageListHeaderWidget", "class_u_message_list_header_widget.html", null ],
    [ "UMessageWidget", "class_u_message_widget.html", null ],
    [ "UReactionGroupBlueprintLibrary", "class_u_reaction_group_blueprint_library.html", null ],
    [ "UReactionsBlueprintLibrary", "class_u_reactions_blueprint_library.html", null ],
    [ "UStreamChatClientComponent", "class_u_stream_chat_client_component.html", null ],
    [ "UStreamChatSettings", "class_u_stream_chat_settings.html", null ],
    [ "UStreamChatWebSocketSettings", "class_u_stream_chat_web_socket_settings.html", null ],
    [ "UTypingIndicatorWidget", "class_u_typing_indicator_widget.html", null ]
];