// Copyright 2026 Stream.IO, Inc. All Rights Reserved.

#pragma once

#include "AdditionalFields.h"
#include "CoreMinimal.h"

#include "Attachment.generated.h"

struct FAttachmentDto;

/**
 * @brief What kind of content an attachment holds
 * @ingroup StreamChat
 */
UENUM(BlueprintType)
enum class EAttachmentType : uint8
{
    /// A type this version of the SDK does not know about. The raw value is kept in FAttachment::RawType
    Unknown,
    /// A still image, rendered inline
    Image,
    /// Any other uploaded file, offered as a download
    File,
    Video,
    Audio,
    /// A Giphy result, produced by the `/giphy` command
    Giphy,
    /// A preview the backend generated by scraping a URL in the message text
    Link
};

/**
 * @brief A file, image or link attached to a message.
 *
 * Upload content with UChatChannel::UploadFile or UploadImage, then put the URL those return into
 * an attachment and pass it to UChatChannel::SendMessage.
 * @ingroup StreamChat
 */
USTRUCT(BlueprintType)
struct STREAMCHAT_API FAttachment
{
    GENERATED_BODY()

    FAttachment() = default;
    explicit FAttachment(const FAttachmentDto&);

    /// Convert back into the wire format for sending
    FAttachmentDto ToDto() const;

    /**
     * @brief The URL of the attached content, whichever field the backend populated.
     *
     * Images arrive in ImageUrl and everything else in AssetUrl, so callers that just want
     * something to fetch should use this rather than picking a field.
     */
    FString GetUrl() const;

    /// Kind of content, used to decide how to display it
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Stream Chat|Attachment")
    EAttachmentType Type = EAttachmentType::Unknown;

    /// Display title, conventionally the original filename
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Stream Chat|Attachment")
    FString Title;

    /// URL of the uploaded file. Set this for non-image attachments
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Stream Chat|Attachment")
    FString AssetUrl;

    /// URL of the uploaded image. Set this for image attachments
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Stream Chat|Attachment")
    FString ImageUrl;

    /// URL of a smaller preview, when the backend generated one. Read-only, set by the backend
    UPROPERTY(BlueprintReadOnly, Category = "Stream Chat|Attachment")
    FString ThumbUrl;

    /// Description text
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Stream Chat|Attachment")
    FString Text;

    /// MIME type of the attached file. Read-only, determined by the backend
    UPROPERTY(BlueprintReadOnly, Category = "Stream Chat|Attachment")
    FString MimeType;

    /// Size of the attached file in bytes. Read-only, determined by the backend
    UPROPERTY(BlueprintReadOnly, Category = "Stream Chat|Attachment")
    int32 FileSize = 0;

    /// The wire value of Type, kept so an unrecognised type still round trips unchanged
    UPROPERTY(BlueprintReadOnly, Category = "Stream Chat|Attachment", AdvancedDisplay)
    FString RawType;

    /// Fields the SDK does not model
    UPROPERTY(BlueprintReadWrite, Category = "Stream Chat|Attachment", AdvancedDisplay)
    FAdditionalFields ExtraData;
};
