// Copyright 2026 Stream.IO, Inc. All Rights Reserved.

#pragma once

#include "Channel/Attachment.h"
#include "CoreMinimal.h"
#include "Moderation/MessageModeration.h"
#include "Reaction/Reactions.h"
#include "Response/Channel/ChannelStateResponseFieldsDto.h"
#include "Response/Message/SearchResultDto.h"
#include "User/UserRef.h"

#include "Message.generated.h"

struct FMessageDto;
struct FMessageRequestDto;

/**
 * @brief The client-side state of a message
 * @ingroup StreamChat
 */
UENUM(BlueprintType)
enum class EMessageSendState : uint8
{
    None,
    /// Message is shown, but user might see a "pending" icon
    Sending,
    /// Message is shown, and user might see a "confirmed" icon
    Sent,
    /// Message is shown, but user might see a "pending" icon
    Updating,
    /// Message might be shown as deleted already, pending confirmation from API
    Deleting,
    /// User might see a "failed" icon
    Failed
};

/**
 * @brief Type of message, as set by the API or chat bots and custom commands.
 * @see https://getstream.io/chat/docs/unreal/message_format/#message-types
 * @ingroup StreamChat
 */
UENUM(BlueprintType)
enum class EMessageType : uint8
{
    /// A regular message created in the channel.
    Regular,
    /// A temporary message which is only delivered to one user. It is not stored in the channel history.
    /// Ephemeral messages are normally used by commands (e.g. `/giphy`) to prompt messages or request for actions.
    Ephemeral,
    /// An error message generated as a result of a failed command.
    /// It is also ephemeral, as it is not stored in the channel history and is only delivered to one user.
    Error,
    /// A message in a reply thread.
    /// @attention The API reports thread replies as Regular, so this does not reliably identify one.
    /// Use FMessage::IsThreadReply(), which goes by ParentId, instead.
    Reply,
    /// A message generated by a system event, like updating the channel or muting a user.
    System,
    /// A soft deleted message
    Deleted
};

/**
 * @brief Represents a Stream Chat message
 * @ingroup StreamChat
 */
USTRUCT(BlueprintType)
struct STREAMCHAT_API FMessage
{
    GENERATED_BODY()

    /// Default construct an invalid message
    FMessage();
    /// Create a message from a DTO from the API
    explicit FMessage(const FMessageDto&, UUserManager*);
    explicit FMessage(const FSearchResultDto&, UUserManager*);
    /// Create a new message from a message string
    explicit FMessage(const FString& Text);
    /// Convert a message into a create/update request for sending to the API.
    /// Takes the channel's CID rather than reading this message's, which is empty until it is sent.
    FMessageRequestDto ToRequestDto(const FString& ChannelCid) const;

    /// Is this message a reply in another message's thread?
    bool IsThreadReply() const;

    /// Does this message have a thread of replies hanging off it?
    bool IsThreadStart() const;

    /**
     * @brief Did moderation bounce this message back to be rephrased?
     *
     * A bounced message was never published and is not stored server side, so it exists only in this
     * client's message list. Offer the author the chance to edit and send it again, or to discard it.
     */
    bool IsBounced() const;

    /// Did moderation block this message and take it out of the channel?
    bool IsRemovedByModeration() const;

    /**
     * @brief Is this the current user's own message, sitting in the list because moderation bounced it?
     *
     * The API reports a bounce as an error-type message, which is how it is told apart from a message
     * that failed to send for some other reason.
     */
    bool IsModerationError() const;

    /// Is this message quoting another one? Look the quoted message up by QuotedMessageId.
    bool IsQuoting() const;

    /**
     * @brief The message text in the given language, falling back to Text when it wasn't translated
     *
     * @param Language A language code as the API names it, e.g. "fr". Matches OriginalLanguage and
     *                 the keys of Translations.
     */
    const FString& GetTranslation(const FString& Language) const;

    /// The message ID. This is either created by the Stream API or set client side when the message is created.
    UPROPERTY()
    FString Id;

    /// CID (<type>:<id>) of the channel the message belongs to.
    /// Empty on a message which hasn't been sent yet.
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    FString Cid;

    /// The text of this message
    UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "Stream Chat|Message")
    FString Text;

    /// Sending state of the message
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    EMessageSendState State = EMessageSendState::None;

    /// User who sent the message
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    FUserRef User;

    /// The message type
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    EMessageType Type = EMessageType::Regular;

    /// The list of user mentioned in the message
    UPROPERTY()
    TArray<FUserRef> MentionedUsers;

    /// Date of first message creation
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    FDateTime CreatedAt = FDateTime{0};

    /// Reserved field indicating when the message was updated last time.
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    FDateTime UpdatedAt = FDateTime{0};

    /// Reserved field indicating when the message was deleted.
    TOptional<FDateTime> DeletedAt;

    /// All reactions of this message, grouped by their type
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    FReactions Reactions;

    /// The message this one is a reply to. Empty if this message is not a reply in a thread.
    /// Set this before sending to start or continue a thread.
    UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "Stream Chat|Message")
    FString ParentId;

    /// Whether this thread reply should also appear in the main channel message list.
    /// Only meaningful together with ParentId.
    UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "Stream Chat|Message")
    bool bShowInChannel = false;

    /// How many replies this message's thread has. Zero unless this message started a thread.
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    int32 ReplyCount = 0;

    /// The users who have replied in this message's thread. Empty unless this message started a thread.
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    TArray<FUserRef> ThreadParticipants;

    UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "Stream Chat|Message", AdvancedDisplay)
    bool bIsSilent = false;

    /// Whether the message was shadowed or not
    UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "Stream Chat|Message", AdvancedDisplay)
    bool bIsShadowed = false;

    /// What moderation decided about this message. Unset on all but a handful of messages.
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message", AdvancedDisplay)
    FMessageModeration Moderation;

    /// Contains HTML markup of the message
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    FString Html;

    /// Files, images and link previews attached to this message
    UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "Stream Chat|Message")
    TArray<FAttachment> Attachments;

    /// The slash command which produced this message, without the slash, e.g. "giphy". Empty for an
    /// ordinary message.
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    FString Command;

    /// Whether this message is pinned in the channel. Set this before sending to pin it.
    UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "Stream Chat|Message")
    bool bPinned = false;

    /// When the message was pinned. Zero unless it is pinned. Stamped by the API.
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    FDateTime PinnedAt = FDateTime{0};

    /// Who pinned the message. Invalid unless it is pinned. Set by the API.
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message")
    FUserRef PinnedBy;

    /// When the pin lapses. Zero for a pin which doesn't expire. Set this before sending to pin the
    /// message for a limited time.
    UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "Stream Chat|Message")
    FDateTime PinExpires = FDateTime{0};

    /// The ID of the message this one quotes. Empty if it quotes nothing.
    /// Set this before sending to quote a message.
    UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "Stream Chat|Message")
    FString QuotedMessageId;

    /// Automatic translations of Text, keyed by language code, e.g. "fr".
    /// Only filled in by an app which has auto-translation switched on.
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message", AdvancedDisplay)
    TMap<FString, FString> Translations;

    /// The language Text was written in, as detected by auto-translation. Empty without it.
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Stream Chat|Message", AdvancedDisplay)
    FString OriginalLanguage;

    UPROPERTY(BlueprintReadWrite, Category = "Stream Chat|Message", AdvancedDisplay)
    FAdditionalFields ExtraData;
};
